Bug fix examples/c/piorcw.c
Compilation fails due to errors in examples/c/piorcw.c.

```
[ 95%] Building C object examples/c/CMakeFiles/piorcw.dir/piorcw.c.o
/home/ec2-user/ParallelIO-pio2_6_0/examples/c/piorcw.c(112): error: "ndims" has already been declared in the current scope
      int ndims, nvars, natts, unlimdim;
          ^

/home/ec2-user/ParallelIO-pio2_6_0/examples/c/piorcw.c(125): error: identifier "i" is undefined
      for(i=0; i<ndims; i++){
          ^

/home/ec2-user/ParallelIO-pio2_6_0/examples/c/piorcw.c(134): error: identifier "myvarname" is undefined
      if(myvarname != NULL)
         ^

/home/ec2-user/ParallelIO-pio2_6_0/examples/c/piorcw.c(224): error: incomplete type is not allowed
      struct arguments arguments;
                       ^

compilation aborted for /home/ec2-user/ParallelIO-pio2_6_0/examples/c/piorcw.c (code 2)
make[2]: *** [examples/c/CMakeFiles/piorcw.dir/piorcw.c.o] Error 2
make[1]: *** [examples/c/CMakeFiles/piorcw.dir/all] Error 2
make: *** [all] Error 2
```

Note there is still a warning when compiling piorcw:

```
/home/ec2-user/ParallelIO/examples/c/piorcw.c(126): warning #167: argument of type "int" is incompatible with parameter of type "MPI_Offset={long long} *"
          ierr = PIOc_inq_dim(ncid, i, dim[i].name, dim[i].value);
```